name: clever_dropdown
description: A customizable Flutter dropdown widget with search, single & multi selection, and add-new-item support.
version: 1.0.0
homepage: https://github.com/fazil-kp/clever_dropdown.git

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  figma_squircle: ^0.6.3
  moon_design: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
